{
  "openapi": "3.0.1",
  "info": {
    "title": "Ecommerce API",
    "version": "1.0.0",
    "description": "The Demo ecommerce api made for user, cart, and order transactions for an art products store."
  },
  "servers": [
    {
      "url": "http://localhost:8000",
      "description": "Main server"
    }
  ],
  "paths": {
    "/api/products": {
      "get": {
        "summary": "Returns all products.",
        "description": "This path gets all products from the database store and returns them in order of id.",
        "operationId": "get_products",
        "tags": ["Products"],
        "responses": {
          "200": {
            "description": "All product objects returned to an array.",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "name": "Abstract cityscape",
                    "author": "Andrej Ostapchuk",
                    "description": "The picture with a volume and a depth of space.",
                    "category": "Abstract",
                    "image_url": "https://d3rf6j5nx5r04a.cloudfront.net/g_4p_c2fVqEA5wws-B8J3xRJsHs=/1120x0/product/6/7/9478e49807e04831a0fff551fe464314_opt.jpg",
                    "status": "Active",
                    "price": 47500
                  },
                  {
                    "id": 2,
                    "name": "Poires et Raisins",
                    "author": "Pascal Giroud",
                    "price": "270.21",
                    "description": "Nature is my greatest source of inspiration.",
                    "category": "Impressionistic",
                    "image_url": "https://d3rf6j5nx5r04a.cloudfront.net/m-1L9HX9Ok69cgTlozcISIJ6efo=/1120x0/product/c/5/f0d3668ec9dc46c3b9f0078195522fcd_opt.jpg",
                    "status": "Active"
                  },
                  "..."
                ]
              }
            }
          }
        }
      }
    },
    "/api/products/{productId}": {
      "get": {
        "summary": "Get the product object by product id.",
        "description": "This path is using id parameter. Product object is fetched from database.",
        "operationId": "get_product_id",
        "tags": ["Products"],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "description": "The id of the product.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns product with id matched to the id parameter.",
            "content": {
              "application/json": {
                "example": {
                  "id": 2,
                  "name": "Poires et Raisins",
                  "author": "Pascal Giroud",
                  "description": "Nature is my greatest source of inspiration.",
                  "category": "Impressionistic",
                  "image_url": "https://d3rf6j5nx5r04a.cloudfront.net/m-1L9HX9Ok69cgTlozcISIJ6efo=/1120x0/product/c/5/f0d3668ec9dc46c3b9f0078195522fcd_opt.jpg",
                  "status": "Active",
                  "price": 27021
                }
              }
            }
          },
          "400": {
            "description": "Error for inavlid product id.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid product number"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/products/categories/{category}": {
      "get": {
        "summary": "Get products in specified category.",
        "description": "This path fetches all products in a category using the category parameter.",
        "operationId": "get_products_categories",
        "tags": ["Products"],
        "parameters": [
          {
            "name": "category",
            "in": "path",
            "description": "Category of products",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns all product objects in the selected category, to an array.",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 14,
                    "name": "Kinko Sennin on a Koi",
                    "author": "Netsuke",
                    "description": "Kinko Sennin on a Koi. Ivory, Meiji-Period (1868 - 1912)",
                    "category": "Netsuke",
                    "image_url": "https://woodblock-print.eu/images/stories/virtuemart/product/CF_N67_Unsterblicher%20mit%20Koi7.jpg",
                    "status": "Sold",
                    "price": 13640
                  },
                  {
                    "id": 15,
                    "name": "Dragon",
                    "author": "Netsuke",
                    "description": "Dragon. Ivory, Meiji-Period (1868 - 1912)",
                    "category": "Netsuke",
                    "image_url": "https://springfieldmuseums.org/wp-content/uploads/2021/01/GWVS_75_23_127_3_sm.jpg",
                    "status": "Active",
                    "price": 76499
                  },
                  {
                    "id": 16,
                    "name": "Raiden, the god of wind, thunder and lightning",
                    "author": "Netsuke",
                    "description": "Netsuke depicting Raiden, the god of wind, thunder and lightning, Japan, 19th century, carved ivory",
                    "category": "Netsuke",
                    "image_url": "http://www.vam.ac.uk/__data/assets/image/0017/236222/2006AL0460_netsuke_main.jpg",
                    "status": "Sold",
                    "price": 10634
                  },
                  "..."
                ]
              }
            }
          },
          "400": {
            "description": "Error for inavlid product category.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid category"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/products/status/{status}": {
      "get": {
        "summary": "Get products in specified product status.",
        "description": "This path fetches all products in a status using the status parameter.",
        "operationId": "get_products_status",
        "tags": ["Products"],
        "parameters": [
          {
            "name": "status",
            "in": "path",
            "description": "Status of products",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns all product objects in the selected status, to an array.",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 5,
                    "name": "Alarm Clock",
                    "author": "BULOVA",
                    "description": "Luminos Hours And Minutes Hands.",
                    "category": "Vintage",
                    "image_url": "https://cdn.shopify.com/s/files/1/0531/9603/0127/products/51vkSBGWynL_540x.jpg?v=1625456846",
                    "status": "active",
                    "price": 8750
                  },
                  {
                    "id": 6,
                    "name": "Antique Wall Clock",
                    "author": "Unknown",
                    "description": "The pendulum wall clocks",
                    "category": "Vintage",
                    "image_url": "https://stylesatlife.com/wp-content/uploads/2021/01/Antique-Clock-Designs-25-Latest-Collection-for-Vintage-Look.jpg",
                    "status": "Active",
                    "price": 13949
                  },
                  "..."
                ]
              }
            }
          },
          "400": {
            "description": "Error for inavlid product status.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid product status"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/products/price/{price}": {
      "get": {
        "summary": "Get products in specified product price.",
        "description": "This path fetches products in a price using the price parameter.",
        "operationId": "get_products_price",
        "tags": ["Products"],
        "parameters": [
          {
            "name": "price",
            "in": "path",
            "description": "Price of products",
            "required": true,
            "schema": {
              "type": "integer",
              "minimum": 1,
              "maximum": 100000,
              "default": 312
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns  product objects in the selected price, to an array.",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 5,
                    "name": "Alarm Clock",
                    "author": "BULOVA",
                    "description": "Luminos Hours And Minutes Hands.",
                    "category": "Vintage",
                    "image_url": "https://cdn.shopify.com/s/files/1/0531/9603/0127/products/51vkSBGWynL_540x.jpg?v=1625456846",
                    "status": "active",
                    "price": 8750
                  },
                  "..."
                ]
              }
            }
          },
          "400": {
            "description": "Error for inavlid product price.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid product price"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/register": {
      "summary": "Input user data to register.",
      "description": "This path is for creating an account to add items to user cart for further purchases.",
      "post": {
        "summary": "Creates an account for a new user.",
        "description": "Creates an account for a new user.",
        "operationId": "post_register",
        "tags": ["Authentication"],
        "requestBody": {
          "description": "Object for creating new user. Password must be at least 6 characters long. Email must match to email syntax.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Registration"
              },
              "example": {
                "email": "test_for_test@example.com",
                "password": "test123456",
                "first_name": "Test",
                "last_name": "Testtest",
                "address": "Test, 00/11",
                "postcode": "010101",
                "city": "Test",
                "country": "Test"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created",
            "content": {
              "text/plain": {
                "example": "User created"
              }
            }
          },
          "400": {
            "description": "Invalid entries in request body",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Email is already in use"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/login": {
      "summary": "Login to your account.",
      "description": "This path is for loging in to your account to access account functions.",
      "post": {
        "summary": "Login to your account.",
        "description": "Enter your email and password to login with Passport and access your user info, cart, and orders. Passport starts a session and keeps you logged in until you send a GET request to /api/logout.",
        "operationId": "post_login",
        "tags": ["Authentication"],
        "requestBody": {
          "description": "Object for logging into account. Password must be at least 6 characters long. Email must match to email syntax.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "example": {
                "email": "test_for_test@example.com",
                "password": "test123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User is logged in.",
            "content": {
              "text/plain": {
                "example": "Token. Message: Test is logged in, customer"
              }
            }
          },
          "400": {
            "description": "Invalid entries in request body.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Email/Password is not found"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/users": {
      "get": {
        "summary": "Returns all users in the database.",
        "description": "This path gets all users from the database store and returns them in order of id.",
        "operationId": "get_users",
        "tags": ["User"],
        "responses": {
          "200": {
            "description": "All users objects returned to an array.",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 42,
                    "email": "2_test_test@example.com",
                    "password": "$*******************************************S",
                    "first_name": "TestTestTest2",
                    "last_name": "TestTestTest2",
                    "address": "TEST11112, 00/11",
                    "postcode": "11112",
                    "city": "TEST11112",
                    "country": "TEST11112",
                    "date_joined": "2022-07-03T17:19:11.849Z",
                    "active": true,
                    "user_role": "customer",
                    "modified": "2022-07-03T21:00:00.000Z"
                  },
                  {
                    "id": 43,
                    "email": "3_test_test@example.com",
                    "password": "$*******************************************A",
                    "first_name": "TestTestTest3",
                    "last_name": "TestTestTest3",
                    "address": "TEST11113, 00/11",
                    "postcode": "11113",
                    "city": "TEST11113",
                    "country": "TEST11113",
                    "date_joined": "2022-07-03T17:24:17.630Z",
                    "active": true,
                    "user_role": "customer",
                    "modified": "2022-07-03T21:00:00.000Z"
                  },
                  {
                    "id": 44,
                    "email": "4_test_test@example.com",
                    "password": "$*******************************************L",
                    "first_name": "TestTestTest4",
                    "last_name": "TestTestTest4",
                    "address": "TEST11114, 00/11",
                    "postcode": "11114",
                    "city": "TEST11114",
                    "country": "TEST11114",
                    "date_joined": "2022-07-04T06:56:45.079Z",
                    "active": true,
                    "user_role": "customer",
                    "modified": "2022-07-03T21:00:00.000Z"
                  },
                  "..."
                ]
              }
            }
          }
        }
      }
    },
    "/api/logout": {
      "summary": "Logs user out.",
      "description": "This path is for logging a user out and ending the session.",
      "get": {
        "summary": "Logs user out",
        "description": "This path is for logging a user out and ending the session.",
        "operationId": "get_logout",
        "tags": ["Authentication"],
        "responses": {
          "200": {
            "description": "User is logged out and ending the session.",
            "content": {
              "text/plain": {
                "example": "Logout is Successful"
              }
            }
          }
        }
      }
    },
    "/api/user/": {
      "summary": "Access user account.",
      "description": "Path for accessing and updating user account information.",
      "get": {
        "summary": "Get user account information.",
        "description": "This path fetches user account information if logged in with Passport. Password not shown with info.",
        "operationId": "get_user",
        "tags": ["User"],
        "responses": {
          "200": {
            "description": "Object is containing user info.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "email": "test_for_test@example.com",
                  "password": "test123456",
                  "first_name": "Test",
                  "last_name": "Testtest",
                  "address": "Test, 00/11",
                  "postcode": "010101",
                  "city": "Test",
                  "country": "Test",
                  "date_joined": "2022-05-18T13:33:52.412Z",
                  "active": true
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update account information.",
        "description": "Update account information if logged in with Passport.",
        "operationId": "put_user",
        "tags": ["User"],
        "requestBody": {
          "description": "Update user data by sending data you want, changed in key value pairs.\nYou can send one or many updates in the same request body.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Registration"
              },
              "examples": {
                "name change": {
                  "value": {
                    "first_name": "Testiko"
                  }
                },
                "email change": {
                  "value": {
                    "email": "test_for_testo@example.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful update response",
            "content": {
              "text/plain": {
                "example": "Update is successful"
              }
            }
          },
          "400": {
            "description": "Information entered does not fit schema.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid entries"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletes user account",
        "description": "This path deletes your account from the database. Make sure you want to delete because there is no any recovery proccess.",
        "operationId": "delete_user",
        "tags": ["User"],
        "responses": {
          "204": {
            "description": "No content - Delete is successful."
          }
        }
      }
    },
    "/api/carts": {
      "description": "Access users carts",
      "get": {
        "summary": "Get user cart information.",
        "description": "This path fetches user cart information; also fetches multiple carts if user has multiple carts. Uses user id from passport Loggin.",
        "operationId": "get_carts",
        "tags": ["Cart"],
        "responses": {
          "200": {
            "description": "Returns array of user's cart object",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Carts"
                },
                "example": [
                  {
                    "id": 4,
                    "user_id": 22,
                    "created_at": "2022-05-18T13:54:53.660Z",
                    "modified": "2022-06-04T10:25:39.235"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "No any carts under your user id",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "No any carts found"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Creates a new cart.",
        "description": "Creates a new cart using the user id provided by your Passport loggin.",
        "operationId": "post_carts",
        "tags": ["Cart"],
        "responses": {
          "201": {
            "description": "Cart is created",
            "content": {
              "text/plain": {
                "example": "Cart is created"
              }
            }
          }
        }
      }
    },
    "/api/carts/{cartId}": {
      "description": "Preform CRUD operations on a cart based on cart id from parameters and user id provided by your Passport loggin.",
      "get": {
        "summary": "Get cart by cart id.",
        "description": "This path fetches user cart information based on cart id and the user id provided by your Passport loggin.",
        "operationId": "get_carts_id",
        "tags": ["Cart"],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns cart object matching to provided cart id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Cart"
                },
                "example": {
                  "id": 3,
                  "user_id": 3,
                  "created": "2022-05-18",
                  "modified": null
                }
              }
            }
          },
          "400": {
            "description": "Invalid cart id.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid cart id"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete cart by cart id.",
        "description": "This path delete cart based on cart id from the parameters and user id provided by your Passport loggin.",
        "operationId": "delete_carts_id",
        "tags": ["Cart"],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No content - cart is deleted"
          }
        }
      }
    },
    "/api/carts/{cartId}/checkout": {
      "get": {
        "summary": "Submit cart for checkout",
        "description": "Creates a new order using all products in the selected cart (parameters) and the user id provided by your Passport loggin.",
        "operationId": "get_carts_checkout",
        "tags": ["Cart/Checkout"],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns id of the new order that was created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Checkout"
                },
                "example": {
                  "order_id": 4
                }
              }
            }
          },
          "400": {
            "description": "No items in cart",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Cart empty. No payment processed"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/carts/{cartId}/items": {
      "get": {
        "summary": "Gets all items in cart",
        "description": "This path fetches all items in the selected cart (cart id from parameter and user id provided by your Passport loggin).",
        "operationId": "get_cart_items",
        "tags": ["Cart/Items"],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "All product objects in cart returned in an array.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductAllCart"
                },
                "example": [
                  {
                    "id": 1,
                    "name": "Abstract cityscape",
                    "author": "Andrej Ostapchuk",
                    "description": "The picture with a volume and a depth of space.",
                    "category": "Abstract",
                    "status": "Active",
                    "quantity": 1
                  },
                  {
                    "id": 15,
                    "name": "Dragon",
                    "author": "Netsuke",
                    "description": "Dragon. Ivory, Meiji-Period (1868 - 1912)",
                    "category": "Netsuke",
                    "status": "Active",
                    "price": 76499,
                    "quantity": 1
                  },
                  "..."
                ]
              }
            }
          },
          "400": {
            "description": "No items in cart",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Cart Empty"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Add item to cart",
        "description": "Add item to the selected cart (cart id from parameter and user id provided by your Passport loggin).",
        "operationId": "post_cart_items",
        "tags": ["Cart/Items"],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Submit product id and quantity in request body.",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductAdd"
              },
              "example": {
                "product_id": 1,
                "quantity": 2
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Item added to cart",
            "content": {
              "text/plain": {
                "example": "Product added"
              }
            }
          },
          "400": {
            "description": "Invalid product id",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid product Id"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/carts/{cartId}/items/{itemId}": {
      "get": {
        "summary": "Get item in cart by item id",
        "description": "This path fetch item from the selected cart (cart id from parameter and user id provided by your Passport loggin) by item id.",
        "operationId": "get_cart_item_id",
        "tags": ["Cart/Items"],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "itemId",
            "in": "path",
            "description": "Product id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns product object that matched input",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductSingleCart"
                },
                "example": {
                  "id": 15,
                  "name": "Dragon",
                  "author": "Netsuke",
                  "description": "Dragon. Ivory, Meiji-Period (1868 - 1912)",
                  "category": "Netsuke",
                  "status": "Active",
                  "price": 76499,
                  "quantity": 1
                }
              }
            }
          },
          "400": {
            "description": "Product with selected id not in cart",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Product not found"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update item quantity in cart",
        "description": "Update item quantity in selected cart (cart id from parameter and user id provided by your Passport loggin.) by item id.",
        "operationId": "put_cart_item_id",
        "tags": ["Cart/Items"],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "itemId",
            "in": "path",
            "description": "Product id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Submit updated quantity in request body.",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateQty"
              },
              "example": {
                "quantity": 5
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Quantity is updated successfully",
            "content": {
              "text/plain": {
                "example": "Quantity is updated"
              }
            }
          },
          "400": {
            "description": "Product with selected id is not in the cart",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Product is not found"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Removes item from cart",
        "description": "Removes item from selected cart (cart id from parameter and user id provided by your Passport loggin) by item id.",
        "operationId": "delete_cart_item_id",
        "tags": ["Cart/Items"],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "itemId",
            "in": "path",
            "description": "Product id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No content - Delete is successful"
          }
        }
      }
    },
    "/api/orders": {
      "get": {
        "summary": "Get all orders.",
        "description": "This path fetches all orders for your account. User id for fetching accounts is provided by your Passport loggin.",
        "operationId": "get_orders",
        "tags": ["Orders"],
        "responses": {
          "200": {
            "description": "All order objects sent in an array.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OrdersAll"
                },
                "example": [
                  {
                    "id": 3,
                    "user_id": 22,
                    "status": "PENDING",
                    "created_at": "2022-05-18T15:41:11.354Z",
                    "modified": "2022-05-24T18:15:40.269Z",
                    "total_price": "$712,500.00"
                  },
                  {
                    "id": 4,
                    "user_id": 22,
                    "status": "PENDING",
                    "created_at": "2022-05-21T11:46:44.626Z",
                    "modified": "2022-05-24T18:16:20.614Z",
                    "total_price": "$189,990.00"
                  },
                  {
                    "id": 5,
                    "user_id": 22,
                    "status": "PENDING",
                    "created_at": "2022-05-21T12:01:18.897Z",
                    "modified": "2022-05-24T18:16:42.857Z",
                    "total_price": "$25,056.00"
                  },
                  "..."
                ]
              }
            }
          },
          "400": {
            "description": "No orders found.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "No orders found"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/orders/{orderId}": {
      "get": {
        "summary": "Get order by order id.",
        "description": "This path fetches an order from your account (user id provided by your Passport loggin) that matches the order id provided (parameters).\nProducts in order are attached in an array to the order object.",
        "operationId": "get_orders_id",
        "tags": ["Orders"],
        "parameters": [
          {
            "name": "orderId",
            "in": "path",
            "description": "Order id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns order object with id matching the parameters. Products in order are attatched in array.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Order"
                },
                "example": {
                  "id": 3,
                  "user_id": 22,
                  "status": "PENDING",
                  "created_at": "2022-05-18T15:41:11.354Z",
                  "modified": "2022-05-24T18:15:40.269Z",
                  "total_price": "$712,500.00",
                  "products": [
                    {
                      "order_items": "(3,1,15,\"$712,500.00\")",
                      "product_id": 1,
                      "quantity": 15
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Order with that id is not found",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Order is not found"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Registration": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "postcode": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "country": {
            "type": "string"
          }
        }
      },
      "Login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "postcode": {
            "type": "integer"
          },
          "city": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "date_joined": {
            "type": "date"
          },
          "active": {
            "type": "string"
          }
        }
      },
      "Carts": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "user_id": {
              "type": "integer"
            },
            "created": {
              "type": "string"
            },
            "modified": {
              "type": "string"
            }
          }
        }
      },
      "Cart": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "user_id": {
            "type": "integer"
          },
          "created": {
            "type": "string"
          },
          "modified": {
            "type": "string"
          }
        }
      },
      "Checkout": {
        "type": "object",
        "properties": {
          "order_id": {
            "type": "integer"
          }
        }
      },
      "ProductAllCart": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "author": {
              "type": "string"
            },
            "price": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "quantity": {
              "type": "integer"
            }
          }
        }
      },
      "ProductAdd": {
        "type": "object",
        "properties": {
          "product_id": {
            "type": "integer"
          },
          "quantity": {
            "type": "integer"
          }
        }
      },
      "ProductSingleCart": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "price": {
            "type": "string"
          },
          "category": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "quantity": {
            "type": "integer"
          }
        }
      },
      "UpdateQty": {
        "type": "object",
        "properties": {
          "quantity": {
            "type": "integer"
          }
        }
      },
      "OrdersAll": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "user_id": {
              "type": "integer"
            },
            "order_price": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "created": {
              "type": "string"
            },
            "modified": {
              "type": "string"
            }
          }
        }
      },

      "Order": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "user_id": {
            "type": "integer"
          },
          "order_price": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "created": {
            "type": "string"
          },
          "modified": {
            "type": "string"
          },

          "products": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "author": {
                  "type": "string"
                },
                "price": {
                  "type": "string"
                },
                "category": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "quantity": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    }
  }
}
